# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1011, 497)
        MainWindow.setStyleSheet("background-color: rgb(102, 204, 204);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, 70, 271, 20))
        self.label.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.botonCargar = QtWidgets.QPushButton(self.centralwidget)
        self.botonCargar.setGeometry(QtCore.QRect(180, 120, 101, 31))
        self.botonCargar.setObjectName("botonCargar")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(70, 250, 341, 31))
        self.textEdit.setObjectName("textEdit")
        self.resultadoCadena = QtWidgets.QLabel(self.centralwidget)
        self.resultadoCadena.setGeometry(QtCore.QRect(334, 470, 321, 31))
        self.resultadoCadena.setText("")
        self.resultadoCadena.setObjectName("resultadoCadena")
        self.botonAceptar = QtWidgets.QPushButton(self.centralwidget)
        self.botonAceptar.setGeometry(QtCore.QRect(180, 310, 101, 31))
        self.botonAceptar.setObjectName("botonAceptar")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(650, 30, 191, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(130, 210, 271, 20))
        self.label_3.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.tablaTransiciones = QtWidgets.QTableWidget(self.centralwidget)
        self.tablaTransiciones.setGeometry(QtCore.QRect(460, 70, 521, 341))
        self.tablaTransiciones.setObjectName("tablaTransiciones")
        self.tablaTransiciones.setColumnCount(4)
        self.tablaTransiciones.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tablaTransiciones.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaTransiciones.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaTransiciones.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaTransiciones.setHorizontalHeaderItem(3, item)
        self.tipoAutomata = QtWidgets.QLabel(self.centralwidget)
        self.tipoAutomata.setGeometry(QtCore.QRect(20, 370, 211, 21))
        self.tipoAutomata.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.tipoAutomata.setObjectName("tipoAutomata")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(250, 370, 211, 20))
        self.label_5.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.tipoCadena = QtWidgets.QLabel(self.centralwidget)
        self.tipoCadena.setGeometry(QtCore.QRect(260, 370, 181, 21))
        self.tipoCadena.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.tipoCadena.setObjectName("tipoCadena")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1011, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Seleccione el automata a cargar"))
        self.botonCargar.setText(_translate("MainWindow", "Subir"))
        self.botonAceptar.setText(_translate("MainWindow", "Aceptar"))
        self.label_2.setText(_translate("MainWindow", "Tabla de transiciones"))
        self.label_3.setText(_translate("MainWindow", "Ingrese cadena a evaluar"))
        item = self.tablaTransiciones.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Pasos"))
        item = self.tablaTransiciones.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Estado Actual"))
        item = self.tablaTransiciones.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Simbolo De Entrada"))
        item = self.tablaTransiciones.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Nuevo Estado"))
        self.tipoAutomata.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.tipoCadena.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
